---
- hosts: all
  become: yes
  tasks: 
  - name: i want to install java on ubuntu nodes
    apt:
     name: openjdk-8-jre 
     state: present
    when: ansible-os-family=="debian"

  - name: i want to install java on ubuntu nodes
    yum: 
     name: java-1.8.0-openjdk
     state: present
    when: ansible-os-family=="RedHat"

  